services:
  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      # - ROOT_PATH=/api/v1
      - PG_HOST=db
      - PG_PASSWORD=some_passwd
      - DEBUG=1
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
  db:
    image: "postgres:16-alpine"
    restart: always
    environment:
      - POSTGRES_PASSWORD=some_passwd
